### ISSUE TITLE
Custom metric for step_umap

### ISSUE THREAD

**Issue by jackobenco016** [tidymodels/embed#155]
Hello,

How can I use a custom metric for the step_umap function (like dice by example) ? 

Have a good day,
Thanks

**Comment by EmilHvitfeldt** [comment]
Hello @jackobenco016 👋 

As far as I'm aware, `uwot::umap()` doesn't allow someone to supply a custom metric. Since `step_umap()` uses `uwot::umap()` it won't be able to do it either. You can file an issue over at https://github.com/jlmelville/uwot to request that feature. If they make it happen, then I'll make it work over here as well!
